apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  labels:
    app: github-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      containers:
      - name: github-runner
        image: benjvi/github-runner-arm:latest
        env:
        - name: GITHUB_OWNER
          value: benjvi
        - name: GITHUB_REPOSITORY
          value: rpi-k8s
        - name: GITHUB_PAT # stored separately in a Kubernetes secret
          valueFrom:
            secretKeyRef:
              name: gh-runner-pat
              key: pat
